/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asw.instagnam.common.api.event;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
